function addBackButton() {
    return `<button class="w3-button w3-orange w3-ripple w3-margin" onclick="window.history.back()">Back</button>`;
}

function addHomeButton() {
    return `<button class="w3-button w3-orange w3-ripple w3-margin" onclick="window.location.href='http://localhost:7777/'">Back</button>`;
}

exports.homePage = function(d) {
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Home</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-blue">
                    <h1>Welcome</h1>
                </header>
                <div class="w3-container">
                    <ul>
                        <li><a href="/alunos">Students</a></li>
                    </ul>
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated on ${d}</h5>
                </footer>
            </div>
        </body>
    </html>`;
};

exports.studentsListPage = function(slist, d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Management</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1>Students List
                    <a class="w3-btn w3-round w3-grey" href="/registos/alunos">+ Add new student</a>
                    </h1>
                </header>
                ${addHomeButton()}
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th><th>GitLink</th>
                            <th>Actions</th>
                        </tr>`;
    for(let i = 0; i < slist.length; i++) {
        pagHTML += `
                <tr>
                    <td>${slist[i].id}</td>
                    <td>
                        <a href="/alunos/${slist[i].id}">
                            ${slist[i].nome}
                        </a>
                    </td>
                    <td>${slist[i].git}</td>
                    <td>
                        [<a href="/alunos/edit/${slist[i].id}">Edit</a>][<a href="/alunos/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>`;
    }
    pagHTML += `
            </table>
            </div>
            <footer class="w3-container w3-teal">
                <h5>Generated by RPCW2025 in ${d}</h5>
            </footer>
            </div>
        </body>
    </html>`;
    return pagHTML;
};

exports.studentFormPage = function(d) {
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Student Form</h2>
                </header>
                ${addBackButton()}
                <form class="w3-container" method="POST" action="/alunos/registo">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" required/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" required/>
                        <label>Git</label>
                        <input class="w3-input w3-round" type="text" name="git" required/>
                    </fieldset>
                    <fieldset>
                        <legend>TPC</legend>
                        <input class="w3-check" type="checkbox" name="tpc1" value="1"/>
                        <label>TPC1</label>
                        <input class="w3-check" type="checkbox" name="tpc2" value="1"/>
                        <label>TPC2</label>
                        <input class="w3-check" type="checkbox" name="tpc3" value="1"/>
                        <label>TPC3</label>
                        <input class="w3-check" type="checkbox" name="tpc4" value="1"/>
                        <label>TPC4</label>
                        <input class="w3-check" type="checkbox" name="tpc5" value="1"/>
                        <label>TPC5</label>
                        <input class="w3-check" type="checkbox" name="tpc6" value="1"/>
                        <label>TPC6</label>
                        <input class="w3-check" type="checkbox" name="tpc7" value="1"/>
                        <label>TPC7</label>
                        <input class="w3-check" type="checkbox" name="tpc8" value="1"/>
                        <label>TPC8</label>
                    </fieldset>  
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>
                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2025 in ${d} - [<a href="/">Home</a>]</h5>
                </footer>
            </div>
        </body>
    </html>`;
};


exports.studentFormEditPage = function(a, d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-orange">
                    <h2>Student Form</h2>
                </header>
                ${addBackButton()}
                <form class="w3-container" method="POST" action="/alunos/edit/${a.id}">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${a.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${a.nome}"/>
                        <label>Git</label>
                        <input class="w3-input w3-round" type="text" name="git" value="${a.git}"/>
                    </fieldset>
                    <fieldset>
                        <legend>TPC</legend>`;
    for (let i = 1; i < 9; i++) {
        let tpc = "tpc" + i;
        if (tpc in a) {
            pagHTML += `<input class="w3-check" type="checkbox" name="tpc${i}" value="1" checked/>
                        <label>TPC${i}</label>`;
        } else {
            pagHTML += `<input class="w3-check" type="checkbox" name="tpc${i}" value="1"/>
                        <label>TPC${i}</label>`;
        }
    }
    pagHTML += `
                    </fieldset>  
                    <br/>
                    <button class="w3-btn w3-orange w3-mb-2" type="submit">Edit</button>
                </form>
                <footer class="w3-container w3-orange">
                    <h5>Generated by EngWeb2025 in ${d} - [<a href="/">Home</a>]</h5>
                </footer>
            </div>
        </body>
    </html>`;
    return pagHTML;
};

exports.successPage = function() {
    return `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8"/>
        <link rel="stylesheet" href="w3.css"/>
        <title>Success</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-green">
                <h1>Registration Completed</h1>
            </header>
            <div class="w3-container">
                <p>The student was successfully registered!</p>
            </div>
            <footer class="w3-container w3-green">
                <a href="/alunos" class="w3-button w3-round w3-grey">Back to student list</a>
            </footer>
        </div>
    </body>
    </html>`;
};

exports.editSuccessPage = function() {
    return `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8"/>
        <link rel="stylesheet" href="w3.css"/>
        <title>Success</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-green">
                <h1>Edit Completed</h1>
            </header>
            <div class="w3-container">
                <p>The student was successfully updated!</p>
            </div>
            <footer class="w3-container w3-green">
                <a href="/alunos" class="w3-button w3-round w3-grey">Back to student list</a>
            </footer>
        </div>
    </body>
    </html>`;
};

// ---------------Student's Page--------------------------------
exports.studentPage = function(aluno, d) {
    var pagHTML = `
    <html>
    <head>
        <title>Aluno: ${aluno.Id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-pink">
                <h1>Aluno ${aluno.id}</h1>
            </header>
            ${addBackButton()}
            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${aluno.nome}</li>
                    <li><b>Número: </b> ${aluno.id}</li>
                    <li><b>Git (link): </b> <a href="${aluno.git}">${aluno.git}</a></li>
                </ul>
            </div>
            <div class="w3-container w3-margin-8">
                <ul class="w3-ul">`;
    for(let i = 1; i < 9; i++) {
        let key = `tpc${i}`;
        if(key in aluno) {
            pagHTML += `
                        <li><b>TPC${i}</b></li>`;
        }
    }
    pagHTML += `</ul></div>
            <footer class="w3-container w3-pink">
                <address>Gerado por galuno::RPCW2022 em ${d} - [<a href="/">Home</a>]</address>
            </footer>
        </div>
    </body>
    </html>`;
    return pagHTML;
};

// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d) {
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Error</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h2>Erro</h2>
                </header>
                ${addBackButton()}
                <div class="w3-container">
                    <p>${d}: ${errorMessage}</p>
                </div>
                <footer class="w3-container w3-red">
                    <h5>Generated by EngWeb2025 in ${d} - [<a href="/">Home</a>]</h5>
                </footer>
            </div>
        </body>
    </html>`;
};
